<?php

include_once('atrium_book.features.inc');

/**
 * Implementation of hook_help().
 */
function atrium_book_help($path, $arg) {
  if (($path == 'help#atrium_book') || context_isset('context', 'spaces-feature-book')) {
    switch ($path) {
      case 'node/add/book':
      case 'node/%/edit':
        $help = '';
        $help .= '<h3>'. t('Notebook') .'</h3>';
        $help .= '<p>'. t('Tips for adding & editing book pages:') .'</p>';
        $help .= '<ul>';
        $help .= '<li>'. t('Create a new book or choose an existing one for your page.') .'</li>';
        $help .= '<li>'. t('Select a position for your page in the book\'s hierarchy and <strong>weight</strong> your page higher or lower if you would like to move it before or after other pages around it.') .'</li>';
        $help .= '<li>'. t('Consider adding a <strong>log message</strong> when editing existing pages so others can get a quick summary of changes you have made.') .'</li>';
        $help .= '</ul>';
        return $help;

      case 'help#atrium_book':
      default:
        $help = '';
        $help .= '<h3>'. t('Notebook') .'</h3>';
        $help .= '<p>'. t('The notebook section provides a way for you to store and share information with your group members. With the book feature you can:') .'</p>';
        $help .= '<ul>';
        $help .= '<li>'. t('!add_book_pages and organize them hierarchically into different books.', array('!add_book_pages' => l(t('Add book pages'), 'node/add/book'))) .'</li>';
        $help .= '<li>'. t('Attach files to pages to share them with others.') .'</li>';
        $help .= '<li>'. t('Track changes that others have made and revert changes as necessary.') .'</li>';
        $help .= '<li>'. t('!archive books that are no longer of interest to the group. Archived books can be reactivated later if needed.', array('!archive' => l(t('Archive'), 'notebook/archived'))) .'</li>';
        $help .= '</ul>';
        return $help;
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function atrium_book_menu() {
  $items = array();
  $items['notebook'] = array(
    'title' => 'Notebook',
    'page callback' => 'atrium_book_overview',
    'page arguments' => array(),
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'atrium_book'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'atrium_book.pages.inc',
  );
  $items['notebook/overview'] = array(
    'title' => 'Overview',
    'page callback' => 'atrium_book_overview',
    'page arguments' => array(),
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'atrium_book'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'file' => 'atrium_book.pages.inc',
  );
  $items['features/atrium_book'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('atrium_book_settings'),
    'access callback' => 'spaces_access_admin',
    'access arguments' => array(),
    'type' => MENU_CALLBACK,
    'file' => 'atrium_book.pages.inc',
  );
  return $items;
}
