<?php

include_once('atrium_blog.features.inc');

/**
 * Implementation of hook_help().
 */
function atrium_blog_help($path) {
  // Central help page content.
  if ($path == 'help#atrium_blog') {
    $help = '<h3>'. t('Blog') .'</h3>';
    $help .= '<p>'. t("The blog lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
    $help .= '<p>'. t("To start a conversation navigate to the blog and click the \"Add blog post\" button. You will need to enter a title and some body content to your post. Then click \"Save\".") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'spaces-feature-blog')) {
    if ($path == 'node/add/blog') {
      $help = '';
      $help .= '<h3>'. t('Blog') .'</h3>';
      $help .= '<p>'. t("Post an entry to the blog of this group. The post will be shared will all team members on the blog, and they will be able to reply to it. You can optionally notify other group members by checking their name in the notifications field.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Blog') .'</h3>';
      $help .= '<p>'. t("The blog lets your team communicate by posting updates and discussing issues. It is a great place for sharing progress, discussing challenges, and exploring ideas.") .'</p>';
      return $help;
    }
  }
}

/**
 * Preprocessor for theme('node_form').
 */
function atrium_blog_preprocess_node_form(&$vars) {
  if (!empty($vars['form']['field_referenced_book_page'])) {
    $vars['sidebar']['field_referenced_book_page'] = $vars['form']['field_referenced_book_page'];
    unset($vars['form']['field_referenced_book_page']);
  }
}
